### ISSUE TITLE
Website download Linux link is broken

### ISSUE THREAD

**Issue by rafaelstz** [zeit/hyper-website#63] opened 2016-12-02 21:11 UTC
The link of Linux version in the website is broken.

![image](https://cloud.githubusercontent.com/assets/610598/20850224/40f61736-b8c1-11e6-97c0-15afa49534b4.png)

**Comment by CodeTheory** [comment] 2016-12-02 21:15
This is a duplicate of #47. You can download the latest release of Hyper for Linux [here](https://github.com/zeit/hyper/releases/latest).

The next release of Hyper will come really soon which fixes the issue with releases and will enable the Linux download link to work again. 😄

**Closed by CodeTheory** 2016-12-02 21:15 UTC
